#spring.application.name=pradnyasanskar-webstore-backend
#
## PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/pharma_shop_db
#spring.datasource.username=postgres
#spring.datasource.password=Sakshi@2005
#
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## JPA
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
## Server
#server.port=8081
#
## JWT Configuration
#jwt.secret=MySuperSecretKeyForPradnyaSanskarWebStoreJWTKey123456789
#jwt.expiration=86400000
#
## =========================
## Swagger / OpenAPI
## =========================
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html
#
#springdoc.swagger-ui.operationsSorter=method
#springdoc.swagger-ui.tagsSorter=alpha
#
#springdoc.default-produces-media-type=application/json
#springdoc.default-consumes-media-type=application/json


spring.application.name=pradnyasanskar-webstore-backend

# PostgreSQL
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=${PORT:8081}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.default-produces-media-type=application/json
springdoc.default-consumes-media-type=application/json